View tasks
alpha-coders-team/todo-app pull request #31
Opened 2021-03-16 07:57 UTC by blkvk

- Добавил страницу просмотра задачи
- Добавил возможность переходить на страниц задачи с главной страницы
- Страницу задачи может просматривать только ее автор
- Пока не отображается история модификации задач

2021-03-16 11:17 UTC, vavsar requested changes
1. Нужно договориться, пишем мы на классах или на функциях
2. Поправить незначительные огрехи

2021-03-16 11:17 UTC, vavsar commented on ToDo/tasks/urls.py
> +    path('<str:username>/<int:post_id>/', views.view_task, name='view-task'),
Вместо int:post_id лучше использовать slug:slug и в модели прописать get_absolute_url. Тогда в адресной строке будет отображаться название объекта, а не непонятные цифры

2021-03-16 11:17 UTC, vavsar commented on ToDo/tasks/views.py
> +def view_task(request, username, post_id):
Раз уж мы начали проект с использованием ClassBasedView, то лучше его в таком духе и продолжать. Присмотрись к классу DetailView

2021-03-16 11:17 UTC, vavsar commented on ToDo/templates/tasks/single_task.html
> +{% extends "base.html" %}
Название темплейта все-таки не "единственная задача", а "детальный просмотр задачи"

2021-03-16 11:17 UTC, vavsar commented on ToDo/tasks/views.py
> +    return redirect('index')
Т.е. если ты не автор задачи, то тебя молча отправит на главную без каких-либо объяснений?

2021-03-16 11:17 UTC, vavsar commented on ToDo/templates/tasks/index.html
> +            <li><a name="task_{{ post.id }}" href="{% url 'view-task' task.owner.username task.id %}">{{ task.title }}</a></li>
Тут можно воспользоваться тегом include и включить карточку задачи на отображение

2021-03-17 05:49 UTC, blkvk commented on ToDo/templates/tasks/index.html
> +            <li><a name="task_{{ post.id }}" href="{% url 'view-task' task.owner.username task.id %}">{{ task.title }}</a></li>
В задачи указано отображение задачи на отдельной странице, но, в принципе, можно сделать детальное отображение на главной странице с возможностью перехода на отдельную. Если это сейчас необходимо, то сделаю

2021-03-17 05:49 UTC, blkvk commented on ToDo/tasks/urls.py
> +    path('<str:username>/<int:post_id>/', views.view_task, name='view-task'),
Не совсем понял. В каком виде должен получится итоговый url?

2021-03-17 07:04 UTC, vavsar commented on ToDo/tasks/urls.py
> +    path('<str:username>/<int:post_id>/', views.view_task, name='view-task'),
У тебя сейчас урл в браузере будет выглядеть так: http://127.0.0.1:8000/andrey/2
Я предлагаю сделать так: http://127.0.0.1:8000/andrey/vstavat-v-8-utra

2021-03-17 07:05 UTC, vavsar commented on ToDo/tasks/urls.py
> +    path('<str:username>/<int:post_id>/', views.view_task, name='view-task'),
Это просто необязательное предложение

2021-03-17 07:06 UTC, vavsar commented on ToDo/templates/tasks/index.html
> +            <li><a name="task_{{ post.id }}" href="{% url 'view-task' task.owner.username task.id %}">{{ task.title }}</a></li>
Это просто необязательное предложение

2021-03-17 11:06 UTC, blkvk commented on ToDo/tasks/views.py
> +    return redirect('index')
Если через хэндлер обработать и сделать обычную вью функцию, а не ViewClassBased, то это будет нормально? Или вью для хэндлеров тоже лучше описать через классы?

2021-03-17 11:17 UTC, vavsar commented on ToDo/tasks/views.py
> +    return redirect('index')
на мой взгляд, в этом варианте в принципе странно написано было. Ты вроде и так запрашиваешь задачи конкретного пользователя, откуда бы взяться чужим и соответственно редиректу. При CBV ты тоже кверисет задаешь с фильтром и чужие нам не выдаются

2021-03-17 13:13 UTC, blkvk commented on ToDo/tasks/views.py
> +    return redirect('index')
если в юрл попробую открыть чужой таск, то он откроется. Например, я под своим аккаунтом попытаюсь посмотреть твою задачу и на отдельной странице она откроется. Поэтому и сделал ограничение. Мы пока не делаем различные режима доступа, поэтому просто реализовал проверку на автора. 
Возможно, я тебя не совсем понимаю. Поправь, если что.

2021-03-17 14:37 UTC, vavsar requested changes
Есть более простой вариант ограничить выдачу объектов: def get_object
Если получится, то соответственно функции "запрещения" и темплейт про доступ будут не нужны.

2021-03-17 14:37 UTC, vavsar commented on ToDo/tasks/views.py
> +    def test_func(self):
Если в представлении определить метод get_object и в нем задать выдачу объектов текущего юзера, тогда вместо чужих задач будет выдаваться 404 страница.
Тогда по ссылке (или кнопке), будут выдаваться только нужные задачи, а чужие будут "отсутствовать"

2021-03-17 14:37 UTC, vavsar commented on ToDo/tasks/views.py
> +    template_name = 'tasks/detail_task_view.html'
Если не задавать имя темплейта, то по умолчанию будет искать название task_detail.html

2021-03-17 14:37 UTC, vavsar commented
Просьба, те комментарии, которые были уже решены, удалять нажатием на Resolve conversation

2021-03-17 19:01 UTC, vavsar approved these changes
slug_field = 'id'  - это не ошибка, т.к. id = pk. Но логически режет глаз, т.к. в урле ты передаешь pk, а в представлении используешь id.

2021-03-18 16:53 UTC, merged