Добавление категории задачи
alpha-coders-team/todo-app pull request #33
Opened 2021-03-18 17:03 UTC by myagkova

Добавила модель категории
Создала форму для создания задачи и добавления новой категории
Добавила вывод категории на главную страницу

2021-03-19 07:50 UTC, igor-markin reviewed
Есть нюансы

2021-03-19 07:50 UTC, igor-markin commented on ToDo/templates/tasks/index.html
> +            <li><a name="task_{{ post.title }}" href="{{ task.get_absolute_url }}">{{ task.title }} -- {{ task.category }}</a></li>
Откуда у нас post.title появился? Понимаю, что ты его не добавляла, но никаких постов у нас нет.

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +    class Meta:
Класс Мета должен стоять после определений формы и до магических методов

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +        max_length=30, required=False, label="New Category Name"
Метку можно написать на русском. Вроде везде пока так делаем. Если что, потом добавим интернационализацию.

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/models.py
> +        related_name='task_category',
лучше написать related_name='tasks', чтобы потом можно было вывести удобно задачи из категории запросом category.tasks

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/models.py
> +        on_delete=models.CASCADE,
При удалении категории нам не нужно удалять все связанные задачи, можно просто проставить в этих полях Null

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +        max_length=30, required=False, label="New Category Name"
Можно хотя бы 50 символов оставить, чтобы не сильно ограничивать пользователя, а можно и все 100.

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +    new_category = forms.CharField(
Лучше убрать приставку new_. Зачем нам, кстати отдельно прописывать категорию, если мы из модели можем её забрать?

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +        self.fields['category'].required = False
Кажется, мы уже указывали в модели требования для категории

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +        if not category:
Здесь не будет ошибки при такой последовательности условий?

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/forms.py
> +    def clean(self):
Джанго по-умолчанию не чистит данные формы, в которой поля унаследованы от модели?

2021-03-19 07:50 UTC, igor-markin commented on ToDo/tasks/models.py
>          ordering = ('deadline', 'priority',)
Можно добавить третью сортировку по категориям

2021-03-20 21:16 UTC, myagkova commented on ToDo/tasks/forms.py
> +    class Meta:
forms удалила

2021-03-20 21:16 UTC, myagkova commented on ToDo/tasks/forms.py
> +        max_length=30, required=False, label="New Category Name"
forms удалила

2021-03-20 21:16 UTC, myagkova commented on ToDo/tasks/forms.py
> +    new_category = forms.CharField(
forms удалила

2021-03-20 21:16 UTC, myagkova commented on ToDo/tasks/forms.py
> +    new_category = forms.CharField(
forms удалила

2021-03-20 21:17 UTC, myagkova commented on ToDo/tasks/forms.py
> +        max_length=30, required=False, label="New Category Name"
forms удалила

2021-03-20 21:17 UTC, myagkova commented on ToDo/tasks/forms.py
> +        self.fields['category'].required = False
forms удалила

2021-03-20 21:18 UTC, myagkova commented on ToDo/tasks/forms.py
> +    def clean(self):
forms удалила

2021-03-20 21:18 UTC, myagkova commented on ToDo/tasks/models.py
>          ordering = ('deadline', 'priority',)
добавила

2021-03-20 21:18 UTC, myagkova commented on ToDo/tasks/forms.py
> +        if not category:
forms удалила

2021-03-20 21:19 UTC, myagkova commented on ToDo/tasks/models.py
> +        on_delete=models.CASCADE,
заменила на models.SET_NULL

2021-03-20 21:19 UTC, myagkova commented on ToDo/tasks/models.py
> +        related_name='task_category',
done

2021-03-20 21:23 UTC, myagkova commented on ToDo/templates/tasks/index.html
> +            <li><a name="task_{{ post.title }}" href="{{ task.get_absolute_url }}">{{ task.title }} -- {{ task.category }}</a></li>
исправила имя

2021-03-20 21:26 UTC, myagkova commented
Убрала форму и сделала добавление категории через модель

2021-03-30 19:30 UTC, vavsar requested changes

2021-04-02 14:39 UTC, blkvk reviewed
В целом все хорошо, но надо подтянуть изменения и обновить PR, чтобы не произошло конфликтов при мердже.

2021-04-04 10:41 UTC, Gaikanomer9 commented
@myagkova все получается с обновлением PR?

2021-04-07 10:22 UTC, myagkova commented
> @myagkova все получается с обновлением PR?

у меня возникла проблема с build-tests, тест builder-image прошел. Не очень понимаю как это исправить.

2021-04-07 12:41 UTC, Gaikanomer9 commented
Отлично, это ошибка из-за того что файлы миграций были удалены. Можешь провести миграции (python manage.py makemigrations) и закоммитить их в PR? И перед этим вернуть файл ToDo/tasks/migrations/0001_initial.py (он в мастере так и остался)

2021-04-07 12:42 UTC, Gaikanomer9 commented
Я скоро выдам всем доступы и тогда мы будем видеть ошибки билдеров в GCP

2021-04-07 14:04 UTC, myagkova commented
> Отлично, это ошибка из-за того что файлы миграций были удалены. Можешь провести миграции (python manage.py makemigrations) и закоммитить их в PR? И перед этим вернуть файл ToDo/tasks/migrations/0001_initial.py (он в мастере так и остался)

Тесты прошли, только с разным статусом

2021-04-07 21:35 UTC, Gaikanomer9 commented
@myagkova извини, что снова тревожу, но надо подтянуть последние изменения из мастера.
Можно сделать через rebase, но там будет скорее всего уйма конфликтов (например, в твоей ветке разошлись миграции 0001 для tasks, а в мастере уже до 0003 они дошли.
Второй вариант это создать чистую ветку и в нее добавить заново изменения, а эту уже закрыть тогда


Это скорее исключение из правил, потому что я много настраивал работу с миграциями, в дальнейшем будем такое гладко делать и без лишних движений 🙇‍♂️

2021-04-08 15:38 UTC, myagkova commented
> @myagkova извини, что снова тревожу, но надо подтянуть последние изменения из мастера.
> Можно сделать через rebase, но там будет скорее всего уйма конфликтов (например, в твоей ветке разошлись миграции 0001 для tasks, а в мастере уже до 0003 они дошли.
> Второй вариант это создать чистую ветку и в нее добавить заново изменения, а эту уже закрыть тогда
> 
> Это скорее исключение из правил, потому что я много настраивал работу с миграциями, в дальнейшем будем такое гладко делать и без лишних движений

2021-04-08 15:38 UTC, closed without merging

2021-04-08 15:42 UTC, myagkova commented
@Gaikanomer9 я скопировала оригинальные миграции из мастера и добавила свою. Такой вариант возможен с сохранением текущей ветки?